default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: 5000

development:
  rideshare:
    <<: *default
    database: rideshare_development
    url: <%= ENV['DATABASE_URL_PRIMARY'] %>
    schema_search_path: rideshare
  rideshare_replica:
    <<: *default
    database: rideshare_development
    url: <%= ENV['DATABASE_URL_REPLICA'] %>
    schema_search_path: rideshare
    replica: true
    database_tasks: true

test:
  <<: *default
  url: postgresql://postgres:@localhost/rideshare_test
